Keycache config
scitokens/scitokens-cpp pull request #105
Opened 2023-01-12 15:40 UTC by jhiemstrawisc

First pass at creating keycache config api.

2023-01-20 14:19 UTC, bbockelm requested changes
Second round is looking good!

Only significant request is to change the function-based interface to a generic config key-based interface.

So, instead of:
```
keycache_set_update_interval_s(300, &err)
```

we should have a function call along the lines of:

```
config_set_int("keycache.update_interval_s", 300, &err)
```

This does remove the type safety of the interface but provides more forward/backward compatibility as adding or removing config variable names does not change the API/ABI.

When adding the new config function, please add a unit test covering the case of a non-existing key as well.

Thanks!

2023-01-20 21:07 UTC, bbockelm approved these changes
LGTM.

Fixes #86

2023-01-21 02:21 UTC, djw8605 commented
There's some minor conflicts from the massive async addition.  Could you resolve the conflicts, then I think we're good to go.

2023-01-30 17:48 UTC, djw8605 commented
A few build errors.

2023-01-30 17:49 UTC, djw8605 commented on src/scitokens_internal.cpp
> +        next_update = now + next_update_delta;
next_update and expires doesn't exist.  Go ahead and put them right into the status->m_next_update and status->m_expires variables.

2023-02-02 12:37 UTC, bbockelm commented
@jhiemstrawisc - can you take another look at this one?  Needs a rebase after the big code churns in the last few weeks.

2023-02-02 22:03 UTC, jhiemstrawisc commented
Rebase done, checks passed!

2023-02-03 18:03 UTC, djw8605 commented
I've merged in the linter check, and the code doesn't pass.  It did annotate the pull request, though, without useful comments.

I wonder if auto-fix is the only way forward?  Since annotations do not give suggested changes?

2023-02-22 14:22 UTC, jhiemstrawisc commented
I'm closing this PR because the git history was damaged. See the new PR #111 to replace this one.

2023-02-22 14:22 UTC, closed without merging